const rawData = [
  {
    name: "Group1RCBandMI",
    enrollments: [0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    monthLabels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
  {
    name: "Group2MIandCSK",
    enrollments: [0, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    monthLabels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
  {
    name: "GroupCSKandKKR",
    enrollments: [0, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    monthLabels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
];
export default rawData;
